name: Python Code Check

# When to run: on every push to the main branch
on:
  push:
    branches: [ “main” ]
  pull_request:
    branches: [ “main” ]

jobs:
  lint:
    runs-on: ubuntu-latest # GitHub provides with an Ubuntu server

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Download code to the GitHub server

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: “3.11”

    - name: Install Linter
      run: pip install flake8 # Police of Python code

    - name: Run Lint Check
    # Check the file for syntax errors
      run: flake8 monitor.py --count --select=E9,F63,F7,F82 --show-source --statistics